PrintComment: Removing some unnecessary mods that just don't add to the game
DeleteFolder:
- plugins/KGvalheim-MagicOverhaul
- plugins/OdinPlus-BasementJVLedition
- plugins/OdinPlus-BuildIt
- plugins/OdinPlus-OdinArchitect/OdinArchitect
- plugins/OdinPlus-PotionPlus
- plugins/RockerKitten-BoneAppetit
